directory: /data/music
library: /data/musiclibrary.db

paths:
  default: Albums/%title{$albumartist}/$album%aunique{}/$track $title
  singleton: Singles/%title{$artist}/$title
  comp: Compilations/$album%aunique{}/$track $title

plugins:
  - webm3u
  - smartplaylist
  - ytimport

webm3u:
  host: 127.0.0.1
  port: 8339
  playlist_dir: /data/playlists

smartplaylist:
  auto: false
  output: m3u8
  playlist_dir: /data/playlists
  relative_to: /data/playlists
  playlists:
  - name: all.m3u8
    query: ''

ytimport:
  directory: /data/ytimport
